### ISSUE TITLE
Assets in Dist for production build

### ISSUE THREAD

**Issue by jamiejamiebobamie** [sprakash57/create-react-saga#18]
Hi!

Thanks for the great npm module! It let me get started with my app right away.

I'm having some issues though with my assets after I build. The project builds, but the built app doesn't know where the media assets are in the assets folder. I've used your webpack build instructions (I believe), but the built project just has transparent / invisible assets, not even a question mark "cannot find image" symbol.

If you could take a look at my repo, I'd really appreciate it: https://github.com/jamiejamiebobamie/dead-writers.

My project is very media / asset heavy so without them, it is just a black screen.

**Comment by sprakash57** [comment]
Hey, Apologies for the delay in response. I am currently busy with my full-time job. I would suggest you to take a look at `webpack.common.js` rules. Specially this one -
`{ test: /\.(png|jpe?g|gif|svg|ico)$/, use: [{ loader: 'file-loader?name=assets/imgs/[name].[ext]' }] },`

`name` should have an exact path. Also you might wanna include video type as well. Currently, CRS has by default `png|jpe?g|gif|svg|ico`

**Comment by jamiejamiebobamie** [comment]
Hey! Thanks for the response!

I spoke to a friend of mine and he showed me how to reference my media files with the "import" keyword and webpack.

It was completely new to me so I wasn't entirely sure.

Thanks for a great npm module!

I'm a noob so this might not be necessary but you might want to consider putting a hyperlink in your docs for people who have never used webpack before.

I was confused even after reading your documentation on how to reference my media files. It appeared as though I needed to edit the webpack file itself, but i think that is on my end!

Thanks again.

**Comment by sprakash57** [comment]
Noted. I will try to improve the documentation. Maybe I will add more details about webpack and asset files. Thanks for the valuable feedback.

**Comment by sprakash57** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create React Saga - Q3.22 update](https://trello.com/c/V4WmhT8H/73-create-react-saga-q322-update)
