### ISSUE TITLE
Add workflow to verify pull requests

### ISSUE THREAD

**Issue by sprakash57** [sprakash57/create-react-saga#23]
The idea here is to test the below steps through a workflow (maybe GitHub action or app)-
* run `npx create-react-saga my-project`
* cd my-project
* npm run build

These steps should pass once a PR is raised against the `master` branch. I am not sure how much of it is possible. I am open to suggestions as well.

**Comment by MeerHamza1421** [comment]
Hey 👋, Is this pipeline for npm?

**Comment by sprakash57** [comment]
Yup. That's right. The idea here is to test the below steps -

1. run `npx create-react-saga my-project` 
2. cd my-project
3. npm start

These steps should pass once a PR is raised against `master` branch.

**Comment by MeerHamza1421** [comment]
I'm a bit confused here. Aren't we supposed to implement a pipeline to automate the npm publish process?

**Comment by sprakash57** [comment]
I see. Looking at the issue description what I told you before doesn't make sense. Well, I will update the issue title and description. I am looking for a workflow to verify pull requests against the `master` branch.

But I liked the suggestion you gave to automate the publishing process. I guess that will have to wait for now.

**Comment by MeerHamza1421** [comment]
Oh ok now its clear, I can write a workflow for it but you are supposed to add/provide test cases, otherwise, workflow would be fail and the pull request won't be verified

**Comment by sprakash57** [comment]
> Oh ok now its clear, I can write a workflow for it but you are supposed to add/provide test cases, otherwise, the workflow would fail and the pull request won't be verified

Is It possible not to include any step regarding unit test cases? Workflow should only cover above mentioned steps.

**Comment by MeerHamza1421** [comment]
I think it's not possible to test a pull request in that way or I think it does not make any sense to test the requests in that way. We have to write unit tests to check pull requests.

**Comment by sprakash57** [comment]
In that case, let me do more R&D and figure out what would be other alternatives to it. Meanwhile, If you want you can contribute to other issues.
