### ISSUE TITLE
[dev-ts]Add eslint and prettier support to the typescript template

### ISSUE THREAD

**Issue by sprakash57** [sprakash57/create-react-saga#26]
Typescript template should have -

- [ ] Eslint support and eslintrc file.
- [ ] Prettier support and prettierrc file.
- [ ] npm command in script section to do manual formatting (e.g - `npm run format`).
- [ ] npm command in script section to do lint fixes (eg - `npm run lint-fix`).

**P.S - Pull Request should be raised against `dev-ts` branch**

**Comment by zurda** [comment]
Hi there, happy to do this one, if available

**Comment by sprakash57** [comment]
Sure. go ahead.

**Comment by sprakash57** [comment]
Hey, @zurda are you still working on it?
