### ISSUE TITLE
[doc]Update Feedback & Suggestions from support

### ISSUE THREAD

**Issue by sprakash57** [sprakash57/create-react-saga#32]
visit the documentation https://sprakash57.github.io/create-react-saga/#/support and edit the `Feedback & Suggestions` section with the below details -

> Do you have any feedback/idea/suggestion to improve create-react-saga? Post them here https://github.com/sprakash57/create-react-saga/discussions

**P.S - Please raise a PR against `gh-pages` branch.**

**Comment by rajdama** [comment]
I can do it

**Comment by Devenkapoor7303** [comment]
Hey, can I work on this issue? If anyone is not working on it?

**Comment by sprakash57** [comment]
I will tag people on a first come first serve basis. Since it's a hacktoberfest specific ticket I will assign them from 1st October onwards.

**Comment by Devenkapoor7303** [comment]
okay

**Comment by sprakash57** [comment]
@rajdama Hey, I have assigned it to you. Let me know if you are still interested in doing this. Otherwise I will give it to others.

**Comment by rajdama** [comment]
@sprakash57  I am interested in doing this.

**Comment by sprakash57** [comment]
Hey @rajdama are you still working on it?

**Comment by sprakash57** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create React Saga v1.x](https://trello.com/c/sPky5ksQ/34-create-react-saga-v1x)

**Comment by sprakash57** [comment]
commit [115e45](https://github.com/sprakash57/create-react-saga/commit/115e45395407d855e3afc8f63441db95d4ef6ff2) takes care of it. Closing this!!
