### ISSUE TITLE
[dev-ts]Absolute import support

### ISSUE THREAD

**Issue by sprakash57** [sprakash57/create-react-saga#34]
The `import` statement should support the absolute path for the typescript template.

Expected -
`import Components/MyComponent`

Actual -
`import ../../../../MyComponent` :(

I would suggest avoiding extra files or extra npm libraries. See if webpack can help to achieve this.

**P.S - Raise PR against `dev-ts` branch**

**Comment by biswain2309** [comment]
Could you please assign this issue to me?

**Comment by sprakash57** [comment]
Yup. Assigned!!

**Comment by sprakash57** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create React Saga v1.x](https://trello.com/c/sPky5ksQ/34-create-react-saga-v1x)
