### ISSUE TITLE
[Template] Remove usage of jsonplaceholder API

### ISSUE THREAD

**Issue by sprakash57** [sprakash57/create-react-saga#47]
## What?

Let's remove the usage the [jsonplaceholder](https://jsonplaceholder.typicode.com) API from the generated code. It will reduce some dependencies on external resources.

## How?

We can use GitHub's own branch to store a simple JSON file and fetch it on button click. The API could be `https://raw.githubusercontent.com/sprakash57/<repo>/<branch_name>/<file_name>.json`.

** This should be fixed for both the template `dev-ts` and `dev-js`. There has to be two PRs targeting specific branches.

- [x] Changes for dev-ts
- [x] Changes for dev-js

**Comment by sprakash57** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create React Saga - Q3.22 update](https://trello.com/c/V4WmhT8H/73-create-react-saga-q322-update)

**Comment by biswain2309** [comment]
Or better, we can use `gist` to store fake data.

**Comment by sprakash57** [comment]
Sure, go ahead @biswain2309. I have created a gist for the same.
